version: "1.0"
services:
    db:
        container_name: art_db
        image: mongo:latest
        environment:
          MONGO_INITDB_ROOT_USERNAME: 'admin'
          MONGO_INITDB_ROOT_PASSWORD: 'pass'
        volumes:
            - ${PWD}/db_data:/data/db
        ports:
            - "27017:27017"
        networks:
            - app-network
    app:
        container_name: art_app
        depends_on:
            - db
        build: .
        # command: npm run serve
        volumes:
            - ${PWD}/app:/usr/app
        links:
            - "db"
        ports:
            - "3000:3000"
        environment:
            DB_HOST: db
            DB_USER: "admin"
            DB_PASSWORD: "pass"
            DB_PORT: "27017"
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
